Improvements and changes in reported cases
Sadi01/yii2-bi-dashboard pull request #42
Opened 2024-03-07 07:28 UTC by MohsenSaeidiDev

2024-03-09 10:08 UTC, Sadi01 requested changes

2024-03-09 10:08 UTC, Sadi01 commented on src/assets/bidashboard/dist/css/custom.css
> +.btn-red{
use bootstrap classes, class="alert alert-danger"

2024-03-09 10:08 UTC, Sadi01 commented on src/controllers/ReportWidgetController.php
> +            ->all();
use model relations

2024-03-09 10:08 UTC, Sadi01 commented on src/migrations/m240302_082109_add_slave_id_column_to_report_year_table.php
> +class m240302_082109_add_slave_id_column_to_report_year_table extends Migration
Consider slave_id in migration, use report_widget table, slave_id column

2024-03-09 10:08 UTC, Sadi01 commented on src/models/ReportBoxWidgets.php
> +            self::FORMAT_KILOGRAM =>Yii::$app->formatter->asWeight($value),
$value / 1000 . KiloGram

2024-03-09 10:08 UTC, Sadi01 commented on src/models/ReportPage.php
> +                self::FORMAT_KILOGRAM => Yii::t('biDashboard', 'Kilo Gram'),
$value / 1000 . KiloGram

2024-03-09 10:08 UTC, Sadi01 commented on src/models/ReportPageWidget.php
> +                return Yii::$app->formatter->asWeight($value);
$value / 1000 . KiloGram

2024-03-09 10:08 UTC, Sadi01 commented on src/models/ReportPageWidget.php
>                  return Yii::$app->formatter->asInteger($value);
replace with utility function in helper class

2024-03-09 10:08 UTC, Sadi01 commented on src/views/report-dashboard/box_table.php
> +                                    <option value="<?= $i ?>" <?= $box->lastRunDate['month'] == $i ? 'selected' : '' ?> ><?= $pdate->jdate_words(['mm' => $i])['mm'] ?></option>
Yii::$app->formatter->asDatetime($i, 'mm');

2024-03-09 10:08 UTC, Sadi01 commented on src/views/report-dashboard/view.php
> -HighchartsAsset::register($this)->withScripts(['modules/stock', 'modules/exporting', 'modules/drilldown']);
check remote or local?

2024-03-10 07:48 UTC, MohsenSaeidiDev commented on src/assets/bidashboard/dist/css/custom.css
> +.btn-red{
used!

2024-03-11 11:53 UTC, MohsenSaeidiDev commented on src/migrations/m240302_082109_add_slave_id_column_to_report_year_table.php
> +class m240302_082109_add_slave_id_column_to_report_year_table extends Migration
Done!

2024-03-11 11:58 UTC, MohsenSaeidiDev commented on src/models/ReportBoxWidgets.php
> +            self::FORMAT_KILOGRAM =>Yii::$app->formatter->asWeight($value),
Done!

2024-03-11 11:59 UTC, MohsenSaeidiDev commented on src/models/ReportPage.php
> +                self::FORMAT_KILOGRAM => Yii::t('biDashboard', 'Kilo Gram'),
Done!

2024-03-11 12:01 UTC, MohsenSaeidiDev commented on src/models/ReportPageWidget.php
> +                return Yii::$app->formatter->asWeight($value);
Done!

2024-03-12 04:55 UTC, MohsenSaeidiDev commented on src/models/ReportPageWidget.php
>                  return Yii::$app->formatter->asInteger($value);
in the future!

2024-03-12 06:05 UTC, MohsenSaeidiDev commented on src/views/report-dashboard/box_table.php
> +                                    <option value="<?= $i ?>" <?= $box->lastRunDate['month'] == $i ? 'selected' : '' ?> ><?= $pdate->jdate_words(['mm' => $i])['mm'] ?></option>
in the future!

2024-03-12 06:56 UTC, Sadi01 commented on src/views/report-dashboard/box_table.php
> +                                    <option value="<?= $i ?>" <?= $box->lastRunDate['month'] == $i ? 'selected' : '' ?> ><?= $pdate->jdate_words(['mm' => $i])['mm'] ?></option>
Yii::$app->formatter->asDatetime(time(), 'MMMM')

2024-03-12 08:12 UTC, Sadi01 commented on src/models/ReportBox.php
> +            self::SCENARIO_UPDATE => ['order', 'dashboard_id', 'display_type', 'title', 'description', 'slave_id', 'chart_type'],
display_order

2024-03-12 10:25 UTC, Sadi01 approved these changes

2024-03-12 10:25 UTC, merged